### ISSUE TITLE
not compile

### ISSUE THREAD

**Issue by Amialc** [auth0-samples/auth0-golang-samples#2]
Sample project [uses](https://github.com/auth0-samples/auth0-golang-samples/blob/master/00-Starter-Seed/regular-web-app/main.go#L4) [github.com/auth0/auth0-golang/examples/regular-web-app/app](https://github.com/auth0/auth0-golang/blob/master/examples/regular-web-app/app/app) which have outdated `app.go` file ([fix for this](https://github.com/auth0/auth0-golang/pull/9/files)) which produce error:
![image](https://cloud.githubusercontent.com/assets/1114365/19162164/7b132b00-8bff-11e6-9842-5da4deaa6598.png)

**Comment by chenkie** [comment]
Fixed in the move to a dedicated [web app sample](https://github.com/auth0-samples/auth0-golang-web-app) and [web API sample](https://github.com/auth0-samples/auth0-golang-web-api).
