### ISSUE TITLE
outdated auth0 lock

### ISSUE THREAD

**Issue by Amialc** [auth0-samples/auth0-golang-samples#3]
Regular web app project [uses outdated lock](https://github.com/auth0-samples/auth0-golang-samples/blob/master/00-Starter-Seed/regular-web-app/routes/home/home.html#L4). Current up-to-date version is 10.2, when used 7.11.

**Comment by chenkie** [comment]
Fixed in the move to a dedicated [web app sample](https://github.com/auth0-samples/auth0-golang-web-app) and [web API sample](https://github.com/auth0-samples/auth0-golang-web-api).
